spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmdm_spring
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mybatis:
  mapper-locations: classpath:mapper/*.xml
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400      # 24 hours
  token-validity-in-seconds-remember-me: 2592000 # 30 days


  hmdm.background.threads: 10
  hmdm.scheduled.threads: 2

logging:
  file:
    name: logs/app.log   # Path & name of your log file
  level:
    root: INFO           # Default logging level for all packages
    com.hmdm: DEBUG  # More verbose logging for your own code


notification:
  mqtt:
    broker: tcp://127.0.0.1:31000
    clientId: server-notifier
    cleanSession: true
    autoReconnect: true
    keepAliveSeconds: 30
    connectTimeoutSeconds: 10
    maxInflight: 50

server:
  servlet:
    context-path=/rest:
