spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmdm_spring
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mybatis:
  mapper-locations: classpath:mapper/*.xml
jwt:
  secret: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6!@#$%^&*()_+-=" # 64 chars for HS512
  token-validity-in-seconds: 86400      # 24 hours
  token-validity-in-seconds-remember-me: 2592000 # 30 days


  hmdm.background.threads: 10
  hmdm.scheduled.threads: 2


