spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmdm_spring
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mybatis:
  mapper-locations: classpath:mapper/*.xml
